services:
  app:
    container_name: fraud_detection
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "9999:9999"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
